breakevenpoint/urls.py
from django.urls import path
from . import views

app_name = 'breakevenpoint'

urlpatterns = [
    path('bep_list',views.BEPListView.as_view(), name="bep_list"),
    path('bep_detail/<pk>',views.BEPDetailView.as_view(), name="bep_detail"),
    path('bep_create',views.BEPCreateView.as_view(), name="bep_create"),
    path('bep_update/<pk>',views.BEPUpdateView.as_view(), name="bep_update"),
    path('bep_delete/<pk>',views.BEPDeleteView.as_view(), name="bep_delete"),
]

v1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/',include('todo.urls')),
    path('', include('website.urls')),
    path('accounts/', include('accounts.urls')),
    path('analysis/', include("breakevenpoint.urls")),
    path('tracker/', include('tracker.urls')),
    path('scrape/', include('aliexpress.urls')),
    path('accounting/', include('accounting.urls')),
    path('transactions/', include('transactions.urls')),
]

templates/bep/bep_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="col-lg-8 mx-auto">
            <h1> {{ delete_what }} {{ object.pk }} </h1>
            
            <form method="post"> {% csrf_token %}
                <p> Sure you want to delete? "{{ object }}" ? </p>
                <input type="submit" value="Delete">
            </form>
        </div>
    </div>

{% endblock %}

templates/bep/bep_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="col-lg-8 mx-auto">
            <h1>  {{ object.pk }} </h1>
            <ul>
                <li> Project Name: {{ object.project_title }}</li>
                <li> Sales:               TND {{ object.sales }}       Units to be Sold: {{ object.units_sold }}</li>
                <li> Variabloe Costs:     TND{{ object.variable_cost }}</li>
                <li> Contribution Margin: TND{{ object.contribution_margin }}       Contribution Ratio: {{ object.contribution_margin_pct }}</li>
                <li> Fixed Costs:         TND{{ object.fixed_cost }}</li>
                <li> Net Income:          TND{{ object.net_income }}</li>
                <li>--------------------------------------------------------------------</li>
                <li> Break Even Point in TND: {{ object.breakevendollar }}</li>
                <li> Break Even Point in Units: {{ object.breakevenunit }}</li>
                {% if object.target_profit  != 0 %}
                    <li> What if Analysis for  Cost Volume Profit Analysis</li>
                    <li> Target Profit:             {{ object.target_profit }} <li> 
                    <li> Break Even Point in TND:   {{ object.targetbepd }}</li>
                    <li> Break Even Point in Units: {{ object.targetbepu }}</li>
                {% endif %}
                
            
            </ul>
            <a href="{% url 'breakevenpoint:bep_update' object.pk %}">Update</a>
            <a href="{% url 'breakevenpoint:bep_delete' object.pk %}">Delete</a>
        
         </div>
    </div>

    <canvas id="myChart" width="10" height="10"></canvas>
        <script>
        var ctx = document.getElementById('myChart').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: ['Red', 'Blue', 'Yellow', 'Green', 'Purple', 'Orange'],
                datasets: [{
                    label: '# of Votes',
                    data: [{{ object.fixed_cost }},{{ object.fixed_cost }},{{ object.fixed_cost }},{{ object.fixed_cost }}, {{ object.fixed_cost }}, {{ object.fixed_cost }}],
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
        </script>

{% endblock %}

templates/bep/bep_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="col-lg-8 mx-auto">
            <form method="post">{% csrf_token %}
                {{ form|crispy}}
                <input type="submit" value="Submit">
            </form>

        </div>
    </div>

{% endblock %}

templates/bep/bep_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="col-lg-8 mx-auto">
            <ul>
                {% for object in object_list %}
                    <li>
                    
                    <a href="{% url 'breakevenpoint:bep_detail' object.pk %}">
                    {{ object.id }} - {{ object.project_title }}</a>
                    </li>
                {% endfor %}


            </ul>

        </div>
    </div>

{% endblock %}