aliexpress/urls.py
from django.urls import path
from . import views
app_name = 'scraper'

urlpatterns = [
    path('add-alibaba',views.scrape_alibaba,name="scrape-alibaba"),
    path('alibaba_list',views.AliBabaListView.as_view(), name="alibaba_list"),
    path('alibaba_detail/<pk>',views.AliBabaDetailView.as_view(), name="alibaba_detail"),
    path('alibaba_delete/<pk>',views.AliBabaDeleteView.as_view(), name="alibaba_delete"),
    path('add-aliexpress',views.scrape_aliexpress,name="scrape-aliexpress"),
    path('aliexpress_list',views.AliExpressListView.as_view(), name="aliexpress_list"),
    path('aliexpress_detail/<pk>',views.AliExpressDetailView.as_view(), name="aliexpress_detail"),
    path('aliexpress_delete/<pk>',views.AliExpressDeleteView.as_view(), name="aliexpress_delete"),
]

v1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/',include('todo.urls')),
    path('', include('website.urls')),
    path('accounts/', include('accounts.urls')),
    path('analysis/', include("breakevenpoint.urls")),
    path('tracker/', include('tracker.urls')),
    path('scrape/', include('aliexpress.urls')),
    path('accounting/', include('accounting.urls')),
    path('transactions/', include('transactions.urls')),
]

templates/scraper/alibaba_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="col-lg-8 mx-auto">
            <h1> {{ object.pk }} </h1>
            
            <form method="post"> {% csrf_token %}
                <p> Sure you want to delete? "{{ object.title }}" ? </p>
                <input type="submit" value="Delete">
            </form>
        </div>
    </div>

{% endblock %}

templates/scraper/alibaba_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="col-lg-8 mx-auto">

            <ul>
                <li> Product Information</li>
                <li> ---------------------- </li>
                <li> ID: {{ object.product_id }}</li>
                <li> Title: {{ object.title }}</li>
                <li> Price From: TND {{ object.price_from }}</li>
                <li> Price To: TND {{ object.price_to }}</li>
                <li> Min Order: {{ object.min_order }}</li>
                <li> Product link: <a href="https:{{ object.link }}" target="_blank">Link</a></li>
                <li> Product Ratings</li>
                <li> ---------------------- </li>
                <li> Product Search: {{ object.product_search }}</li>
                <li> Product Score: {{ object.product_score }}</li>
                <li> Review Count: {{ object.review_count }}</li>
                <li> Review Score: {{ object.review_score }}</li>
                <li> Shipping Time Score: {{ object.shipping_time }}</li>
                <li> Supplier Service: {{ object.supplier_service }}</li>
                <li> Supplier Information</li>
                <li> ---------------------- </li>
                <li> Supplier Name: {{ object.supplier_name }}</li>
                <li> Supplier Link: <a href="https:{{ object.supplier_link }}" target="_blank">Link</a></li>
                <li> Supplier Country: {{ object.supplier_country }}</li>
                <li> Supplier Years: {{ object.supplier_year }}</li>
            </ul>
        
            <a href="{% url 'scraper:alibaba_delete' object.pk %}">Delete</a>
        </div>
    </div>

{% endblock %}

templates/scraper/alibaba_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


        <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Title</th>
                                            <th>Price From</th>
                                            <th>Price To</th>
                                            <th>Min Order</th>
                                            <th>Link</th>
                                            <th>Product Search</th>
                                            <th>Detail</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        
                                    {% for object in object_list %}
                                        <tr>
                                            <td>{{ object.product_id }}</td>
                                            <td>{{ object.title }}</td>
                                            <td>TND {{ object.price_from }}</td>
                                            <td>TND {{ object.price_to }}</td>
                                            <td>{{ object.min_order }}</td>
                                            <td><a href="https:{{ object.link }}" target="_blank">Link</a></td>
                                            <td>{{ object.product_search }}</td>
                                            <td><a href="{% url 'scraper:alibaba_detail' object.pk %}">View Detail</a></td>
                                        </tr>
                                    {% endfor %}           
                                     </tbody>
                                </table>
                                {% if is_paginated %}
                                <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li> 
                                        <span><a href="?page={{ page_obj.previous_page_number }}"> Previous </a></span>
                                    </li>
                                {% endif %}
                                    <li class="">
                                        <span>Page {{ page_obj.number }} Of {{ page_obj.paginator.num_pages}}.</span>
                                    <li>
                                {% if page_obj.has_next %}
                                    <li>
                                        <span><a href="?page={{ page_obj.next_page_number }}">Next</a></span>
                                    </li>
                                {% endif %}
                                </ul>
                                {% endif %}
                            </div>
                        

{% endblock %}

templates/scraper/aliexpress_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="col-lg-8 mx-auto">
            <h1> {{ object.pk }} </h1>
            
            <form method="post"> {% csrf_token %}
                <p> Sure you want to delete? "{{ object.title }}" ? </p>
                <input type="submit" value="Delete">
            </form>
        </div>
    </div>

{% endblock %}

templates/scraper/aliexpress_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="col-lg-8 mx-auto">

            <ul>
                <li> Product Information</li>
                <li> ---------------------- </li>
                <li> ID: {{ object.product_id }}</li>
                <li> Title: {{ object.title }}</li>
                <li> Price: TND {{ object.price }}</li>
                <li> Unit: {{ object.unit }}</li>
                <li> Product Ratings</li>
                <li> ---------------------- </li>
                <li> Product Search: {{ object.product_search }}</li>
                <li> Rating: {{ object.rating }}</li>
                <li> Supplier Information</li>
                <li> ---------------------- </li>
                <li> Supplier Name: {{ object.supplier_name }}</li>
                <li> Supplier Link: <a href="https:{{ object.supplier_link }}" target="_blank">Link</a></li>
            </ul>
        
            <a href="{% url 'scraper:aliexpress_delete' object.pk %}">Delete</a>
        </div>
    </div>

{% endblock %}

templates/scraper/aliexpress_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


        <div class="table-responsive">
                                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>Title</th>
                                            <th>Price</th>
                                            <th>Rating</th>
                                            <th>Product Search</th>
                                            <th>Detail</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        
                                    {% for object in object_list %}
                                        <tr>
                                            <td>{{ object.product_id }}</td>
                                            <td>{{ object.title }}</td>
                                            <td>{{ object.price }}</td>
                                            <td>{{ object.rating }}</td>
                                            <td>{{ object.product_search }}</td>
                                            <td><a href="{% url 'scraper:aliexpress_detail' object.pk %}">View Detail</a></td>
                                        </tr>
                                    {% endfor %}           
                                     </tbody>
                                </table>
                                {% if is_paginated %}
                                <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li> 
                                        <span><a href="?page={{ page_obj.previous_page_number }}"> Previous </a></span>
                                    </li>
                                {% endif %}
                                    <li class="">
                                        <span>Page {{ page_obj.number }} Of {{ page_obj.paginator.num_pages}}.</span>
                                    <li>
                                {% if page_obj.has_next %}
                                    <li>
                                        <span><a href="?page={{ page_obj.next_page_number }}">Next</a></span>
                                    </li>
                                {% endif %}
                                </ul>
                                {% endif %}
                            </div>
                        

{% endblock %}

templates/scraper/scrape_alibaba.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="col-lg-8 mx-auto">
            <form method="post">{% csrf_token %}
                <input class="form-control" name="product">
                <button class="btn btn-primary" type="submit">Scrape Alibaba Products</button>
            </form>

        </div>
    </div>

{% endblock %}

templates/scraper/scrape_aliexpress.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="col-lg-8 mx-auto">
            <form method="post">{% csrf_token %}
                <input class="form-control" name="product">
                <button class="btn btn-primary" type="submit">Scrape AliExpress Products</button>
            </form>

        </div>
    </div>

{% endblock %}