todo/urls.py
from django.urls import path
from . import views

app_name = 'todo'

urlpatterns = [
    path('', views.home, name='home'),
    path('create/', views.createtodo, name='createtodo'),
    path('current/', views.currenttodos, name='currenttodos'),
    path('completed/', views.completedtodos, name='completedtodos'),
    path('todo/<int:todo_pk>', views.viewtodo, name='viewtodo'),
    path('todo/<int:todo_pk>/complete', views.completetodo, name='completetodo'),
    path('todo/<int:todo_pk>/delete', views.deletetodo, name='deletetodo'),
]

v1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/',include('todo.urls')),
    path('', include('website.urls')),
    path('accounts/', include('accounts.urls')),
    path('analysis/', include("breakevenpoint.urls")),
    path('tracker/', include('tracker.urls')),
    path('scrape/', include('aliexpress.urls')),
    path('accounting/', include('accounting.urls')),
    path('transactions/', include('transactions.urls')),
]

website/urls.py
from django.urls import path
from . import views

app_name="website"

urlpatterns = [
    path('',views.index,name="index")
]

templates/base_todo.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="icon" type="image/png"  href="#">
    <title>Genical TodoApp</title>
</head>
<body>


<nav class="navbar navbar-expand-md navbar-light bg-warning">
<div class="container">
    <a class="navbar-brand" href="{% url 'todo:home' %}">
         <img src="#" width="30" height="30" class="d-inline-block align-top">
        <span>Todo Woo</span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">

                <li class="nav-item {{ current }}">
                    <a class="nav-link" href="{% url 'todo:currenttodos' %}">Current</a>
                </li>
                <li class="nav-item {{ completed }}">
                    <a class="nav-link" href="{% url 'todo:completedtodos' %}">Completed</a>
                </li>
                <li class="nav-item {{ create }}">
                    <a class="nav-link" href="{% url 'todo:createtodo' %}">Create</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'website:index' %}">Other Template</a>
                </li>

        </ul>

        
    </div>
</div>
</nav>

<div class="container">
{% block content %}{% endblock %}
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

templates/base_tracker.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <title>Expense Tracker</title>
    <style> 
      @import url('https://fonts.googleapis.com/css?family=Lato&display=swap');

      :root {
        --box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
      }

      * {
        box-sizing: border-box;
      }

      body {
        background-color: #f7f7f7;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        min-height: 100vh;
        margin: 0;
        font-family: 'Lato', sans-serif;
      }

      .container {
        margin: 30px auto;
        width: 350px;
      }

      h1 {
        letter-spacing: 1px;
        margin: 0;
      }

      h3 {
        border-bottom: 1px solid #bbb;
        padding-bottom: 10px;
        margin: 40px 0 10px;
      }

      h4 {
        margin: 0;
        text-transform: uppercase;
      }

      .inc-exp-container {
        background-color: #fff;
        box-shadow: var(--box-shadow);
        padding: 20px;
        display: flex;
        justify-content: space-between;
        margin: 20px 0;
      }

      .inc-exp-container > div {
        flex: 1;
        text-align: center;
      }

      .inc-exp-container > div:first-of-type {
        border-right: 1px solid #dedede;
      }

      .money {
        font-size: 20px;
        letter-spacing: 1px;
        margin: 5px 0;
      }

      .money.plus {
        color: #2ecc71;
      }

      .money.minus {
        color: #c0392b;
      }

      label {
        display: inline-block;
        margin: 10px 0;
      }

      input[type='text'],
      input[type='number'] {
        border: 1px solid #dedede;
        border-radius: 2px;
        display: block;
        font-size: 16px;
        padding: 10px;
        width: 100%;
      }

      .btn {
        cursor: pointer;
        background-color: #9c88ff;
        box-shadow: var(--box-shadow);
        color: #fff;
        border: 0;
        display: block;
        font-size: 16px;
        margin: 10px 0 30px;
        padding: 10px;
        width: 100%;
      }

      .btn:focus,
      .delete-btn:focus {
        outline: 0;
      }

      .list {
        list-style-type: none;
        padding: 0;
        margin-bottom: 40px;
      }

      .list li {
        background-color: #fff;
        box-shadow: var(--box-shadow);
        color: #333;
        display: flex;
        justify-content: space-between;
        position: relative;
        padding: 10px;
        margin: 10px 0;
      }

      .list li.plus {
        border-right: 5px solid #2ecc71;
      }

      .list li.minus {
        border-right: 5px solid #c0392b;
      }

      .delete-btn {
        cursor: pointer;
        background-color: #e74c3c;
        border: 0;
        color: #fff;
        font-size: 20px;
        line-height: 20px;
        padding: 2px 5px;
        position: absolute;
        top: 50%;
        left: 0;
        transform: translate(-100%, -50%);
        opacity: 0;
        transition: opacity 0.3s ease;
      }

      .list li:hover .delete-btn {
        opacity: 1;
      }
  </style>
  </head>
  <body>
    <h2>Expense Tracker</h2>
    <a class="collapse-item" href="{% url 'website:index' %}">Other Template</a>
    {% block content %}
      <div class="container">
      </div>
      <script src="{% static 'js/balance.js'%}"></script>
    {% endblock %}
  </body>
</html>